export const COLORS = {
    BUTTON_PRIMARY_BACKGROUND_COLOR: '#ffffff80',
    BUTTON_PRIMARY_TEXT_COLOR: '#000000',
    BUTTON_SECONDARY_BACKGROUND_COLOR: '#00000050',
    BUTTON_SECONDARY_TEXT_COLOR: '#fff',
    BUTTON_DANGER_BACKGROUND_COLOR: '#ff000080',
    SPINNER_COLOR: '#fff'
}