import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../lib/contexts/auth.context";
import { Toaster } from "sonner";
import AppNavbar from "@/shared/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "StockFlow MVP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col">
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <AppNavbar />
            <div className="flex-1 flex flex-col justify-center items-center">
              {children}
            </div>
          </div>
          <Toaster position="top-center" richColors></Toaster>
        </AuthProvider>
      </body>
    </html>
  );
}
